{
 "title": "Home Dashboard",
 "tags": [ "Percona" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Names",
    "query": {
     "query": "label_values(up{environment=~\"$environment\"}, node_name)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(node_load1{node_type=~\"generic|remote_rds|container|remote\"}, region)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values(up{region=~\"$region\"}, node_type)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|up\",node_name=~\"$node_name\"}, service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Monitored DB Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (id_service) (label_replace(up{node_name=~\"$node_name\",job=~\"mysql.*\",environment=~\"$environment\"}, \"id_service\", \"$2\", \"job\", \"(.*)_exporter_agent_id_(.*)_(.*)\"))) or vector(0)",
     "legendFormat": "MySQL"
    },
    {
     "expr": "count(count by (id_service) (label_replace(up{node_name=~\"$node_name\",job=~\"mongodb.*\",environment=~\"$environment\"}, \"id_service\", \"$2\", \"job\", \"(.*)_exporter_agent_id_(.*)_(.*)\"))) or vector(0)",
     "legendFormat": "MongoDB"
    },
    {
     "expr": "count(count by (id_service) (label_replace(up{node_name=~\"$node_name\",job=~\"postgres.*\",environment=~\"$environment\"}, \"id_service\", \"$2\", \"job\", \"(.*)_exporter_agent_id_(.*)_(.*)\"))) or vector(0)",
     "legendFormat": "PostgreSQL"
    },
    {
     "expr": "count(count by (id_service) (label_replace(up{node_name=~\"$node_name\",job=~\"proxysql.*\",environment=~\"$environment\"}, \"id_service\", \"$2\", \"job\", \"(.*)_exporter_agent_id_(.*)_(.*)\"))) or vector(0)",
     "legendFormat": "ProxySQL"
    }
   ]
  },
  {
   "title": "Monitored DB Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (service_type) (mysql_global_status_uptime{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"})",
     "legendFormat": "MySQL"
    },
    {
     "expr": "count by (service_type) (mongodb_up{region=~\"$region\",node_type=~\"$node_type\",node_name=~\"$node_name\"})",
     "legendFormat": "MongoDB"
    },
    {
     "expr": "count by (service_type)  (group by (service_name, service_type) (pg_up{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"}))",
     "legendFormat": "PostgreSQL"
    },
    {
     "expr": "count by (service_type)  (group by (service_name, service_type) (proxysql_mysql_status_active_transactions{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"}))",
     "legendFormat": "ProxySQL"
    }
   ]
  },
  {
   "title": "Monitored Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (node_name) (up{node_name=~\"$node_name\",region=~\"$region\"})) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Virtual CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(node_cpu_seconds_total{node_name=~\"$node_name\",mode=~\"user\",region=~\"$region\",node_type=~\"$node_type\"}) or \n(1-absent(node_cpu_seconds_total{node_name=~\"$node_name\",mode=~\"user\",region=~\"$region\",node_type=~\"$node_type\"}))) + \nsum(rdsosmetrics_General_numVCPUs{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"} or up * 0)"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "RAM (Random Access Memory) is the hardware in a computing device where the operating system, application programs, and data in current use are kept so the device's processor can quickly reach them. ",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (node_memory_MemTotal_bytes{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"})"
    }
   ]
  },
  {
   "title": "Virtual Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (node_memory_MemTotal_bytes{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"}+node_memory_SwapTotal_bytes{node_name=~\"$node_name\",region=~\"$region\",node_type=~\"$node_type\"})"
    }
   ]
  },
  {
   "title": "Min Node Uptime",
   "type": "stat",
   "description": "Minimal Uptime",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(node_time_seconds{node_name=~\"$node_name\"} - node_boot_time_seconds{node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "Min DB Uptime",
   "type": "stat",
   "description": "Minimal DB Uptime",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by () (mysql_global_status_uptime{node_name=~\"$node_name\"} or \nmongodb_instance_uptime_seconds {node_name=~\"$node_name\"} or \n(time() - process_start_time_seconds{node_name=~\"$node_name\",job=~\"postgres_exporter.*\"}))"
    }
   ]
  },
  {
   "title": "Disk Space Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(avg(node_filesystem_size_bytes{node_name=~\"$node_name\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype))"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (rate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[$interval]) or irate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[5m]) or max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[5m])) * 1024"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (rate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[$interval]) or irate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[5m]) or\nmax_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[5m])) * 1024",
     "legendFormat": "Disk Writes"
    }
   ]
  },
  {
   "title": "Database Connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (sum by (node_name)(mysql_global_status_threads_connected{node_name=~\"$node_name\",environment=~\"$environment\"}[$interval]),\nsum by (node_name)(mongodb_connections{node_name=~\"$node_name\",state=\"current\",environment=~\"$environment\"}[$interval]),\nsum by (node_name) (max_over_time(pg_stat_database_numbackends{node_name=~\"$node_name\",environment=~\"$environment\"}[$interval])),\nsum by (node_name) (proxysql_connection_pool_conn_used{node_name=~\"$node_name\",environment=~\"$environment\"}[$interval]),\nsum by (node_name) (increase(haproxy_frontend_connections_total{node_name=~\"$node_name\",environment=~\"$environment\"}[$interval]))\n)",
     "legendFormat": "Database connections"
    }
   ]
  },
  {
   "title": "Database Query/s (QPS)",
   "type": "stat",
   "description": "Query per second",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by () (\n(rate(mysql_global_status_queries{node_name=~\"$node_name\",environment=~\"$environment\"}[5m]) or \nirate(mysql_global_status_queries{node_name=~\"$node_name\",environment=~\"$environment\"}[5m])), \n(rate(mongodb_op_counters_total{node_name=~\"$node_name\",type!=\"command\",environment=~\"$environment\"}[5m]) or \nirate(mongodb_op_counters_total{node_name=~\"$node_name\",type!=\"command\",environment=~\"$environment\"}[5m])),\n((rate(pg_stat_database_xact_commit{node_name=~\"$node_name\",environment=~\"$environment\"}[5m]) + \nrate(pg_stat_database_xact_rollback{node_name=~\"$node_name\",environment=~\"$environment\"}[5m])) or\n(irate(pg_stat_database_xact_commit{node_name=~\"$node_name\",environment=~\"$environment\"}[5m]) + \nirate(pg_stat_database_xact_rollback{node_name=~\"$node_name\",environment=~\"$environment\"}[5m]))),\n(rate(proxysql_connection_pool_queries{node_name=~\"$node_name\",environment=~\"$environment\"}[5m]) or\nirate(proxysql_connection_pool_queries{node_name=~\"$node_name\",environment=~\"$environment\"}[5m])),\n(rate(haproxy_backend_sessions_total{node_name=~\"$node_name\",environment=~\"$environment\"}[5m]) or irate(haproxy_backend_sessions_total{node_name=~\"$node_name\",environment=~\"$environment\"}[5m])))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Advisors check",
   "type": "pmm-check-panel-home",
   "description": "Display the number of Advisors checks identified as failed during its most recent run.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PMM Upgrade",
   "type": "pmm-update",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Anomaly Detection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Anomalies",
   "type": "stat",
   "description": "Difference between the current CPU value and the CPU value a week ago. Considerable differences in these values result from a significant change in the CPU utilisation of the resources.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk_max(10, ((100 - (avg by (node_name) (rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"idle\"}[5m])) * 100)) > 60) and (100 - (avg by (node_name) (rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"idle\"}[5m])) * 100)) - (100 - (avg by (node_name) (rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"idle\"}[5m])) * 100) offset 1w) > 30)",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "High CPU Servers",
   "type": "stat",
   "description": "CPU usage above 90%",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk_max(10, 100 - (avg by (node_name) (rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"idle\"}[15m])) * 100) > 90)",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Disk Queue Anomalies",
   "type": "stat",
   "description": "Difference between the current Disk Queue value and the value a week ago. Considerable differences result from a significant change in the usage of the Disk queue resource and a warning.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk_max(10, (sum by (node_name) (rate(node_disk_io_time_weighted_seconds_total{node_name=~\"$node_name\"}[$interval])) > 2) and sum by (node_name) (rate(node_disk_io_time_weighted_seconds_total{node_name=~\"$node_name\"}[$interval])) - sum by (node_name) (rate(node_disk_io_time_weighted_seconds_total{node_name=~\"$node_name\"}[$interval])) offset 1w  > 1)",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "High Disk Queue",
   "type": "stat",
   "description": "Disk queue size above <XX> requests, regardless of time.",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk_max(10, sum by (node_name) (rate(node_disk_io_time_weighted_seconds_total{node_name=~\"$node_name\"}[1m])) > 2)",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Used Memory Anomaly",
   "type": "stat",
   "description": "Difference between the current Used Memory value and the value a week ago. Considerable differences result from a significant change in the usage of the Memory resource and a warning.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk_max(10, ((avg by (node_name) ((node_memory_MemTotal_bytes{node_name=~\"$node_name\"} -\n(node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"}))) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100 )) > 80 )and ((avg by (node_name) ((node_memory_MemTotal_bytes{node_name=~\"$node_name\"} -\n(node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"}))) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100 )) - avg by (node_name) ((node_memory_MemTotal_bytes{node_name=~\"$node_name\"} -\n(node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"}))) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100 ) offset 1w > 30))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "High Memory Used",
   "type": "stat",
   "description": "Memory usage above 80% regardless of time",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk_max(10, (avg by (node_name) ((node_memory_MemTotal_bytes{node_name=~\"$node_name\"} -\n(node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"}))) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100 )) > 80)",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Low CPU Anomalies",
   "type": "stat",
   "description": "Difference between the current CPU value and the CPU value a week ago. Considerable differences in these values result from a significant change in the CPU utilisation of the resources.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk_max(10, ((100 - (avg by (node_name) (rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"idle\"}[5m])) * 100)) < 30) and (100 - (avg by (node_name) (rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"idle\"}[5m])) * 100)) - (100 - (avg by (node_name) (rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"idle\"}[5m])) * 100) offset 1w) < 10)",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Low CPU Servers",
   "type": "stat",
   "description": "CPU usage less 30%, regardless of time",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk_min(10, 100 - (avg by (node_name) (rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"idle\"}[15m])) * 100) < 30)",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "COMMAND CENTER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top 20 CPU Usage",
     "type": "timeseries",
     "description": "Measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, called CPU usage.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk_max(20, 100 - (avg by (node_name) (rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"idle\"}[$interval])) * 100))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "CPU Anomaly ",
     "type": "timeseries",
     "description": "Measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, called CPU usage.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(100 - (avg by (node_name) (rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"idle\"}[$interval])) * 100)) - (100 - (avg by (node_name) (rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"idle\"}[$interval])) * 100) offset 1w) ",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 20 CPU Usage (prev week)",
     "type": "timeseries",
     "description": "The CPU time is measured in clock ticks or seconds. This graph shows the top 20. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "topk_max(20,100 - (avg by (node_name) (rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"idle\"}[$interval])) * 100))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 20 Disk Queue",
     "type": "timeseries",
     "description": "Disk loaded for reads or writes as an average number of outstanding requests at different periods. A high disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher loads with no problems.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk_max(20,sum by (node_name) (rate(node_disk_io_time_weighted_seconds_total{node_name=~\"$node_name\"}[$interval])))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Disk Queue Anomaly",
     "type": "timeseries",
     "description": "Disk loaded for reads or writes as an average number of outstanding requests at different periods. A high disk load is a good measure of actual storage utilization. Different storage types handle load differently. For some, latency increases on low loads. Others can handle higher loads with no problems.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by (node_name) (rate(node_disk_io_time_weighted_seconds_total{node_name=~\"$node_name\"}[$interval])) - sum by (node_name) (rate(node_disk_io_time_weighted_seconds_total{node_name=~\"$node_name\"}[$interval])) offset 1w  > 0",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 20 Disk Queue  (prev week)",
     "type": "timeseries",
     "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time. This graph lists the top 20. High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk_max(20,sum by (node_name) (rate(node_disk_io_time_weighted_seconds_total{node_name=~\"$node_name\"}[$interval])))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 20 Write Latency",
     "type": "timeseries",
     "description": "The average latency for Reads and Writes for IO Devices. This graph lists the top 20. Higher than expected latency for highly loaded storage indicates saturation (overload) and is a frequent cause of performance problems. Also, it might indicate internal storage problems.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk_max(20,rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / rate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval]) > 0 )",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Write Latency Anomaly",
     "type": "timeseries",
     "description": "Shows average latency for Reads and Writes IO Devices. Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems. Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / rate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval])) - (rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / rate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval])) offset 1w > 0 ",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 20 Write Latency  (prev week)",
     "type": "timeseries",
     "description": "Shows average latency for Reads and Writes IO Devices. Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems. Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk_max(20,rate(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / rate(node_disk_writes_completed_total{node_name=~\"$node_name\"}[$interval]) > 0 )",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 20 Read Latency",
     "type": "timeseries",
     "description": "Shows average latency for Reads and Writes IO Devices. Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems. Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk_max(20,rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / rate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval]) > 0 )",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Read Latency Anomaly",
     "type": "timeseries",
     "description": "Shows average latency for Reads and Writes IO Devices. Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems. Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / rate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval])) offset 1w - (rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / rate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval])) > 0 ",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 20 Read Latency (prev week)",
     "type": "timeseries",
     "description": "Shows average latency for Reads and Writes IO Devices. Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems. Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk_max(20,rate(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[$interval]) / rate(node_disk_reads_completed_total{node_name=~\"$node_name\"}[$interval]) > 0 )",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Top 20 Used Memory",
     "type": "timeseries",
     "description": "Basic memory usage as a percentage of the available physical memory.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk_max(20, (avg by (node_name) ((node_memory_MemTotal_bytes{node_name=~\"$node_name\"} -\n(node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"}))) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100 )))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Used Memory Anomaly",
     "type": "timeseries",
     "description": "Difference between the current Memory value and the Memory value a week ago. Considerable differences in these values result from a significant change in the Memory utilization of the resources. Big differences are the result of a significant change in the usage of the Memory resource and a warning.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "((avg by (node_name) ((node_memory_MemTotal_bytes{node_name=~\"$node_name\"} -\n(node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"}))) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100 ))) and ((avg by (node_name) ((node_memory_MemTotal_bytes{node_name=~\"$node_name\"} -\n(node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"}))) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100 )) - avg by (node_name) ((node_memory_MemTotal_bytes{node_name=~\"$node_name\"} -\n(node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"}))) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100 ) offset 1w > 0)",
       "legendFormat": "{{node_name}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Top 20 Used Memory  (prev week)",
     "type": "timeseries",
     "description": "Difference between the current Memory value and the Memory value a week ago. Considerable differences in these values result from a significant change in the Memory utilization of the resources. Big differences are the result of a significant change in the usage of the Memory resource and a warning.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "topk_max(20, (avg by (node_name) ((node_memory_MemTotal_bytes{node_name=~\"$node_name\"} -\n(node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"}))) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100 )))",
       "legendFormat": "{{node_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "yesoreyeram-boomtable-panel",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "min by (service_name) (up{node_name=~\"$node_name\",service_type=~\"mysql|mongodb|postgresql|proxysql|haproxy|external\",job=~\".*_hr-.*|^external.*\",environment=~\"$environment\"})",
       "legendFormat": "{{service_name}} | Status"
      },
      {
       "expr": "max by (service_name,node_name) (up{node_name=~\"$node_name\",service_type=~\"mysql\",job=~\".*_hr-.*\",environment=~\"$environment\"})",
       "legendFormat": "{{service_name}} |{{node_name}}|Mysql Type"
      },
      {
       "expr": "(sum by (service_name) (\n(rate(mysql_global_status_queries{node_name=~\"$node_name\",environment=~\"$environment\"}[$interval]) or \nirate(mysql_global_status_queries{node_name=~\"$node_name\",environment=~\"$environment\"}[5m])) or \n(sum by (service_name) (rate(mongodb_op_counters_total{node_name=~\"$node_name\",type!=\"command\",environment=~\"$environment\"}[$interval])) or \nsum by (service_name) (irate(mongodb_op_counters_total{node_name=~\"$node_name\",type!=\"command\",environment=~\"$environment\"}[5m]))) or\n(sum by (service_name) (rate(pg_stat_database_xact_commit{node_name=~\"$node_name\",environment=~\"$environment\"}[$interval]) + \nrate(pg_stat_database_xact_rollback{node_name=~\"$node_name\",environment=~\"$environment\"}[$interval])) or\nsum by (service_name) (irate(pg_stat_database_xact_commit{node_name=~\"$node_name\",environment=~\"$environment\"}[5m]) + \nirate(pg_stat_database_xact_rollback{node_name=~\"$node_name\",environment=~\"$environment\"}[5m])))\n))",
       "legendFormat": "{{service_name}} | DB QPS"
      },
      {
       "expr": "(sum by(service_name)(max_over_time(mysql_global_status_threads_connected{node_name=~\"$node_name\",environment=~\"$environment\"}[$interval]) or \nlabel_replace(mysql_global_status_threads_connected{node_name=~\"$node_name\",node_type=\"remote\",environment=~\"$environment\"},\"node_name\",\"pmm-server\",\"\",\"\") or\nmax_over_time(mongodb_connections{node_name=~\"$node_name\",state=\"current\",environment=~\"$environment\"}[$interval]) or\nsum by (service_name) (max_over_time(pg_stat_database_numbackends{node_name=~\"$node_name\",environment=~\"$environment\"}[$interval]))))",
       "legendFormat": "{{service_name}} | DB Connections"
      },
      {
       "expr": "((clamp_max(avg by (node_name) (sum by (node_name,cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!='idle',mode!=\"iowait\"}[$interval]),1)) or(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!='idle',mode!=\"iowait\"}[5m]),1)) )),1) *100 or\nsum by (node_name) (avg_over_time(node_cpu_average{node_name=~\"$node_name\",mode!=\"idle\", mode!=\"total\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\",mode!=\"idle\", mode!=\"total\"}[5m]))) * on(node_name) group_left(environment, service_name) avg by (node_name, service_name, environment) (up{node_name=~\"$node_name\",service_type=~\"mysql|mongodb|postgresql|proxysql|haproxy|external\",job=~\".*_hr-.*|^external.*\",environment=~\"$environment\"}))",
       "legendFormat": "{{service_name}} |{{node_name}}| CPU Busy"
      },
      {
       "expr": "max by (service_name,node_name) (up{node_name=~\"$node_name\",service_type=~\"postgresql\",job=~\".*_hr-.*\",environment=~\"$environment\"})",
       "legendFormat": "{{service_name}} |{{node_name}}| Postgresql Type"
      },
      {
       "expr": "max by (service_name,node_name) (up{node_name=~\"$node_name\",service_type=~\"mongodb\",job=~\".*_hr-.*\",environment=~\"$environment\"})",
       "legendFormat": "{{service_name}} |{{node_name}}| MongoDB Type"
      },
      {
       "expr": "min by (service_name) (mysql_global_status_uptime{node_name=~\"$node_name\",environment=~\"$environment\"} or \nmongodb_instance_uptime_seconds {node_name=~\"$node_name\",environment=~\"$environment\"} or \n(time() - process_start_time_seconds{node_name=~\"$node_name\",job=~\"postgres_exporter.*\",environment=~\"$environment\"}))",
       "legendFormat": "{{service_name}} | DB Uptime"
      },
      {
       "expr": "(((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} or\n(rdsosmetrics_memory_free{node_name=~\"$node_name\"} + rdsosmetrics_memory_buffers{node_name=~\"$node_name\"} + rdsosmetrics_memory_cached{node_name=~\"$node_name\"})/ rdsosmetrics_memory_total{node_name=~\"$node_name\"}) * 100) * on(node_name) group_left(environment,service_name) (up{node_name=~\"$node_name\",service_type=~\"mysql|mongodb|postgresql|proxysql|haproxy|external\",job=~\".*_hr-.*|^external.*\",environment=~\"$environment\"})",
       "legendFormat": "{{service_name}} |{{node_name}}| Memory Available"
      },
      {
       "expr": "((rate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[$interval]) or irate(node_vmstat_pgpgin{node_name=~\"$node_name\"}[5m]) or sum by (node_name) (max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_readKbPS{node_name=~\"$node_name\"}[5m]))) * 1024) * on(node_name) group_left(environment,service_name) (up{node_name=~\"$node_name\",service_type=~\"mysql|mongodb|postgresql|proxysql|haproxy|external\",job=~\".*_hr-.*|external.*\",environment=~\"$environment\"})",
       "legendFormat": "{{service_name}} |{{node_name}}| Disk Reads"
      },
      {
       "expr": "((rate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[$interval]) or irate(node_vmstat_pgpgout{node_name=~\"$node_name\"}[5m]) or\nsum by (node_name) (max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[$interval]) or max_over_time(rdsosmetrics_diskIO_writeKbPS{node_name=~\"$node_name\"}[5m]))) * 1024)  * on(node_name) group_left(environment,service_name) (up{node_name=~\"$node_name\",service_type=~\"mysql|mongodb|postgresql|proxysql|haproxy|external\",job=~\".*_hr-.*|^external.*\",environment=~\"$environment\"})",
       "legendFormat": "{{service_name}} |{{node_name}}| Disk Writes"
      },
      {
       "expr": "((sum by (node_name) (rate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval]) or\nirate(node_network_receive_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[5m]))) + \n(sum by (node_name) (rate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[$interval]) or \nirate(node_network_transmit_bytes_total{node_name=~\"$node_name\", device!=\"lo\"}[5m])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[$interval])) or \nsum by (node_name) (max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[5m]))))  * on(node_name) group_left(environment,service_name) (up{node_name=~\"$node_name\",service_type=~\"mysql|mongodb|postgresql|proxysql|haproxy|external\",job=~\".*_hr-.*|^external.*\",environment=~\"$environment\"})",
       "legendFormat": "{{service_name}} |{{node_name}}| Network IO"
      },
      {
       "expr": "((count by (node_name) (node_cpu_seconds_total{node_name=~\"$node_name\",mode=~\"user\"}) or (1-absent(node_cpu_seconds_total{node_name=~\"$node_name\",mode=~\"user\"}))) + \nsum by (node_name) (rdsosmetrics_General_numVCPUs{node_name=~\"$node_name\"} or up * 0)) * on(node_name) group_left(environment,service_name) (up{node_name=~\"$node_name\",service_type=~\"mysql|mongodb|postgresql|proxysql|haproxy|external\",job=~\".*_hr-.*|^external.*\",environment=~\"$environment\"})",
       "legendFormat": "{{service_name}} |{{node_name}}| Virtual CPU"
      },
      {
       "expr": "(node_memory_MemTotal_bytes{node_name=~\"$node_name\"} or (rdsosmetrics_memory_total{node_name=~\"$node_name\"}*1024)) * on(node_name) group_left(environment,service_name) (up{node_name=~\"$node_name\",service_type=~\"mysql|mongodb|postgresql|proxysql|haproxy|external\",job=~\".*_hr-.*|^external.*\",environment=~\"$environment\"}) ",
       "legendFormat": "{{service_name}} |{{node_name}}| RAM"
      },
      {
       "expr": "max by (service_name,node_name) (up{node_name=~\"$node_name\",service_type=~\"proxysql\",job=~\".*_hr-.*\",environment=~\"$environment\"})",
       "legendFormat": "{{service_name}} |{{node_name}}|ProxySQL Type"
      },
      {
       "expr": "max by (service_name,node_name) (up{node_name=~\"$node_name\",service_type=~\"haproxy\",job=~\"^external.*\",environment=~\"$environment\"})",
       "legendFormat": "{{service_name}} |{{node_name}}|HAProxy Type"
      }
     ]
    }
   ]
  }
 ]
}