{
 "title": "MongoDB Collection Details",
 "tags": [
  "MongoDB",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"mongodb_up\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_up{environment=~\"$environment\"},cluster)"
    }
   },
   {
    "name": "replset",
    "label": "Replica Set",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{cluster=~\"$cluster\"}, set)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(mongodb_up{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\"}, service_name)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mongodb_up{environment=~\"$environment\",cluster=~\"$cluster\"}, node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Largest Collections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 10 Largest Collections by Document Count",
   "type": "table",
   "description": "Lists the largest collections according to number of documents; helps track growth and look to address possible performance issues.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, avg by (service_name,database,collection) (sum(mongodb_collstats_storageStats_count{service_name=~\"$service_name\"}) by (service_name, database, collection))) > 0",
     "legendFormat": "{{service_name}}.{{ schema }}.{{ table }}"
    }
   ]
  },
  {
   "title": "Top 10 Largest Collections by Size",
   "type": "table",
   "description": "Lists the largest collections according to size; helps track growth and assess need to scale or shard.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, avg by (service_name,database,collection) (sum(mongodb_collstats_storageStats_size{service_name=~\"$service_name\"}) by (service_name, database, collection))) > 0",
     "legendFormat": "{{service_name}}.{{ schema }}.{{ table }}"
    }
   ]
  },
  {
   "title": "Size - $service_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "service_name",
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Databases Size - $service_name",
   "type": "timeseries",
   "description": "Provides the names and sizes databases in an instance/cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (service_name) (sum(max_over_time(mongodb_collstats_storageStats_size{service_name=~\"$service_name\"}[$interval]) or\nmax_over_time(mongodb_collstats_storageStats_size{service_name=~\"$service_name\"}[5m])))",
     "legendFormat": "Data + Index Size"
    }
   ]
  },
  {
   "title": "Top 5 Most Fragmented Collections by Freeable Size - $service_name (MongoDB 5.0+)",
   "type": "table",
   "description": "Lists the most fragmented collections  (storage available for reuse) - ranked by size. Address your largest fragmented collections 1st for performance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, avg by (service_name,database,collection) (sum(mongodb_collstats_storageStats_freeStorageSize{service_name=~\"$service_name\"}) by (database, collection, service_name)))",
     "legendFormat": "{{ service_name }} - {{ database }}.{{ collection }}"
    }
   ]
  },
  {
   "title": "Collection Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "The next two graphs are available only when `--enable-all-collectors` option is used in pmm-admin."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Documents Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 5 Collections by Documents Read",
   "type": "timeseries",
   "description": "Show the 5 collections according to read activity",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, avg by (service_name,database,collection) (rate(mongodb_top_queries_count{service_name=~\"$service_name\"}[$interval]))>0) or \ntopk(5, avg by (service_name,database,collection) (irate(mongodb_top_queries_count{service_name=~\"$service_name\"}[5m]))>0)",
     "legendFormat": "{{service_name}} - {{ database }}.{{ collection }}"
    }
   ]
  },
  {
   "title": "Documents Changed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 5 Collections by Documents Changed",
   "type": "timeseries",
   "description": "Show the 5 collections according to write activity",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, avg by (service_name,database,collection) (rate(sum by (service_name,database,collection) (mongodb_top_insert_count,mongodb_top_update_count,mongodb_top_remove_count{service_name=~\"$service_name\"})[$interval])>0)) or topk(5, avg by (service_name,database,collection) (irate(sum by (service_name,database,collection) (mongodb_top_insert_count,mongodb_top_update_count,mongodb_top_remove_count{service_name=~\"$service_name\"})[5m]))>0)",
     "legendFormat": "{{service_name}} - {{ database }}.{{ collection }}"
    }
   ]
  }
 ]
}