{
 "title": "CPU Utilization Details",
 "tags": [
  "Percona",
  "OS"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values({__name__=~\"node_boot_time_seconds|rdsosmetrics_timestamp|azure_resource_info\"}, node_name)"
    }
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "label_values(node_cpu_seconds_total{node_name=~\"$node_name\"}, cpu)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\",node_name=~\"$node_name\"}, service_name)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$node_name - Overall CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max(avg by (node_name,mode) ((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[5m]),1)) ))*100 or (max_over_time(node_cpu_average{node_name=~\"$node_name\",mode=~\"user|system|wait|steal|irq\"}[$interval]) or max_over_time(node_cpu_average{node_name=~\"$node_name\", mode=~\"user|system|wait|steal|irq\"}[5m]))),100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "clamp_max(max by () ((sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )*100) or (max_over_time(node_cpu_average{node_name=~\"$node_name\", mode=~\"user|system|steal|irq\"}[$interval]) or max_over_time(node_cpu_average{node_name=~\"$node_name\", mode=~\"user|system|steal|irq\"}[5m]))),100)",
     "legendFormat": "Max Core Utilization"
    }
   ]
  },
  {
   "title": "$node_name - Current CPU Threads Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max(avg by () ((sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1))*100 )) or max_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\",mode!=\"idle\", mode!=\"wait\"}[5m])) ,100)",
     "legendFormat": "Avg"
    },
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max((sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m])*100,100)) )) or sum by (cpu) (max_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\",mode!=\"idle\", mode!=\"wait\"}[5m])) ,100)",
     "legendFormat": " {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Threads Frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node_name - CPU Threads Frequency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,cpu) (max_over_time(node_cpu_frequency_hertz{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_cpu_frequency_hertz{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "cpu_{{cpu}}"
      },
      {
       "expr": "avg(max_over_time(node_cpu_frequency_hertz{node_name=~\"$node_name\"}[$interval]) or max_over_time(node_cpu_frequency_hertz{node_name=~\"$node_name\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Current CPU Cores Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node_name - Current CPU Cores Temperature",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "avg(label_replace(sum by (sensor,node_name,chip,cpu) ((node_hwmon_temp_celsius{node_name=~\"$node_name\"})) * on(sensor) group_left(cpu) (sum by (sensor,node_name,cpu) (label_replace(node_hwmon_sensor_label{node_name=~\"$node_name\",label=~\"core.*\"},\"cpu\", \"$1\", \"label\", \"core_(.*)\"))),\"chip\", \"$2\", \"chip\", \"(.*)_coretemp_(.*)\"))",
       "legendFormat": "Avg"
      },
      {
       "expr": "(label_replace(sum by (sensor,node_name,chip,cpu) ((node_hwmon_temp_celsius{node_name=~\"$node_name\"})) * on(sensor) group_left(cpu) (sum by (sensor,node_name,cpu) (label_replace(node_hwmon_sensor_label{node_name=~\"$node_name\",label=~\"core.*\"},\"cpu\", \"$1\", \"label\", \"core_(.*)\"))),\"chip\", \"$2\", \"chip\", \"(.*)_coretemp_(.*)\"))",
       "legendFormat": " cpu{{chip}}-core{{cpu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Overall CPU Threads Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "All Cores - total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum by () ((avg by (mode) ( \n(clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100 or \nsum by () (\navg_over_time(node_cpu_average{node_name=~\"$node_name\",mode!=\"total\",mode!=\"idle\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",mode!=\"total\",mode!=\"idle\"}[5m])) unless\n(avg_over_time(node_cpu_average{node_name=~\"$node_name\",mode=\"total\",job=\"rds-basic\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",mode=\"total\",job=\"rds-basic\"}[5m]))\n),100)"
    }
   ]
  },
  {
   "title": "All Cores - user",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(avg by (node_name,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"user\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"user\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"user\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - system",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(avg by (node_name,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"system\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"system\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"system\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - iowait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(avg by (node_name,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"iowait\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"wait\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"wait\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - steal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(avg by (node_name,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"steal\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"steal\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"steal\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - other",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(((sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100) or (sum(avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[$interval])) or sum(avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[5m])))),100) "
    }
   ]
  },
  {
   "title": "CPU Threads Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Per Core CPU Threads Usage",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "Per CPU usage Information shows  usage for each CPU (Virtual) core.  The Current (most recent) numbers are shown together with history as sparkline"
   }
  },
  { "title": "$cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }, "repeat": "cpu" },
  {
   "title": "$cpu - total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\nsum by (cpu) (\n(avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100) or \nsum by () (\navg_over_time(node_cpu_average{node_name=~\"$node_name\",mode!=\"total\",mode!=\"idle\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",mode!=\"total\",mode!=\"idle\"}[5m])) unless\n(avg_over_time(node_cpu_average{node_name=~\"$node_name\",mode=\"total\",job=\"rds-basic\"}[$interval]) or \navg_over_time(node_cpu_average{node_name=~\"$node_name\",mode=\"total\",job=\"rds-basic\"}[5m]))\n,100)"
    }
   ]
  },
  {
   "title": "$cpu - user",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(avg by (node_name,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",cpu=\"$cpu\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",cpu=\"$cpu\",mode=\"user\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", cpu=\"All\", mode=\"user\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", cpu=\"All\", mode=\"user\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - system",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(avg by (node_name,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",cpu=\"$cpu\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",cpu=\"$cpu\",mode=\"system\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", cpu=\"All\", mode=\"system\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", cpu=\"All\", mode=\"system\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - iowait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(avg by (node_name,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",cpu=\"$cpu\",mode=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",cpu=\"$cpu\",mode=\"iowait\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", cpu=\"All\", mode=\"wait\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", cpu=\"All\", mode=\"wait\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - steal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(avg by (node_name,mode)((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",cpu=\"$cpu\",mode=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",cpu=\"$cpu\",mode=\"steal\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", cpu=\"All\", mode=\"steal\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", cpu=\"All\", mode=\"steal\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - other",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(((sum by (instance) (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100) or (sum(avg_over_time(node_cpu_average{node_name=~\"$node_name\", cpu=\"All\",mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[$interval])) or sum(avg_over_time(node_cpu_average{node_name=~\"$node_name\",cpu=\"All\",mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[5m])))),100)"
    }
   ]
  }
 ]
}