name: CI

on:
  issues:
    types: [opened, edited, milestoned]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Pull changes from the PMM instance
      run: |
        docker pull aemdeveloper/pmm_grafana_backup_tool_test:0.0.2

        docker run --rm \
            -e GRAFANA_TOKEN=${{ secrets.GRAFANA_TOKEN }} \
            -e GRAFANA_URL=${{ secrets.GRAFANA_URL }} \
            -v dashboards:/opt/pmm_grafana_backup_tool/_OUTPUT_  \
            aemdeveloper/pmm_grafana_backup_tool_test:0.0.2
    - name: Create Pull Request with updated dashboards
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: Update PMM dashboards
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>     
        add-paths: |
          dashboards/
        title: Update dashb oards
        body: |
          - Dashboards update
        branch: update-dashboards

